spring:
  datasource:
    url: jdbc:mysql://localhost:3306/final_project
    username: root
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
